### ISSUE TITLE
Teleconnection Variables

### ISSUE THREAD

**Issue by orhuna** [orhuna/ar_ivt#2]
This is a reporting issue for determining the final list of teleconnection variables.

**Closing Criteria **
- [x] List of teleconnection variables

**Comment by kellyrmat** [comment]
# Teleconnection Variables Final List:
- ## Multivariate ENSO Index (MEI)
- ## Madden-Julian Oscillation (MJO)
- ## Pacific North American Pattern (PNA)
- ## North Atlantic Oscillation (NAO)
- ## Quasi-Biennial Oscillation (QBO)
- ## Pacific Meridional Mode (PMM)

**Time series of monthly indices (QBO,PMM,MEI) can be found at this [link](https://psl.noaa.gov/data/climateindices/).**<br>
**Daily time series of the MJO can be found at this [link](http://www.bom.gov.au/climate/mjo/#tabs=Phase).**<br>
**Daily time series of the PNA and NAO can be found at this [link](https://ftp.cpc.ncep.noaa.gov/cwlinks/).**<br>

**Comment by orhuna** [comment]
Closing criteria satisfied. Closing
