### ISSUE TITLE
Georesolution Abstract

### ISSUE THREAD

**Issue by orhuna** [orhuna/ar_ivt#20]
Closing criteria
- [x] FInalized Abstract

**Comment by kellyrmat** [comment]
# A Boosted Decision Tree to Predict Atmospheric River Vapor Transport with Teleconnection Patterns 

Atmospheric Rivers (ARs) sustain the water resources of the Western United States, are prone to substantial interannual variability, and are modulated by intraseasonal climate variability. The extent to which modes of climate variability modulate storm characteristics is an active area of research with potential to extend operational meteorology from days into weeks. We apply an automated detection algorithm to the North American Regional Reanalysis to build a climatology of cool-season, maritime-originating, West Coast atmospheric rivers spanning 1979-2013. Using a gradient-boosted regression tree model, we combine the AR climatology with a suite of teleconnection patterns, ENSO, MJO, QBO, PNA, and PMM, to evaluate the relationships between an AR’s vapor transport and its surrounding climate modes.  We also evaluate the varying importance of certain teleconnection patterns by grouping AR tracks with similar geography. We find that an atmospheric river’s water vapor transport is modulated by a combination of its geography and the underlying large-scale climate background state. In particular, the source region of an AR storm track, its distance travelled, ENSO status, and the strength of the Pacific-North-American Pattern determine the strength of an AR’s water vapor transport. This research is performed at the AI-CHESS Lab at SLU led by Dr. Orhun Aydin.

**Comment by kellyrmat** [comment]
@orhuna Copied from my submission to GeoRes
