### ISSUE TITLE
Georesolution Poster

### ISSUE THREAD

**Issue by orhuna** [orhuna/ar_ivt#21]
- [x] First draft of the poster sent to @orhuna 
- [x] Uploading the final draft.

**Comment by kellyrmat** [comment]
@orhuna Here's a snippet of what I have so far:
![image](https://github.com/orhuna/ar_ivt/assets/114206053/07372b69-21dc-4370-a760-b73efe44ea0f)

---

I've shared the full sized tiff with you in Teams because couldn't add it here.

**Comment by kellyrmat** [comment]
@orhuna Here's a clip of my final poster: 
![image](https://github.com/orhuna/ar_ivt/assets/114206053/efbf50da-1984-43ac-a24e-5612b614dc92)

**Comment by orhuna** [comment]
@kellyrmat ready to close
