### ISSUE TITLE
Boosted Regression Tree Model

### ISSUE THREAD

**Issue by orhuna** [orhuna/ar_ivt#3]
Creating the boosted regression tree model to predict IVT given teleconnection and AR dynamics variables

Closing Criteria:
- [x] Initial model that produces results (nothing more)
- [x] Reporting the R2 and variable importance here in the issue
- [x] Pushing the code to the Github Repo

**Comment by kellyrmat** [comment]
## XGboosted IVT Regression Tree
- ['BulkAxisDi', 'SSD_Theta', 'area', 'length', 'centroid_y',
       'centroid_x', 'PMM', 'QBO', 'MEI', 'Phase', 'Curvature',
       'Displacement', 'origin_lat', 'origin_lon', 'Amplitude',
       'pna_index_cdas', 'nao_index_cdas', 'month'] are predictor variables
- Predicts AR Average IVT with AR dynamics variables and teleconnection patterns
---

## XGboosted IVT regression performance diagram

![image](https://github.com/orhuna/ar_ivt/assets/114206053/eef8a2f3-429b-40b9-abf4-38e57af6765b)
- Training coefficient of determination ~0.80, training is ~0.73. Model is slightly overfit
- Similar bias to what's been seen before, overpredicting low and underpredicting high values
- The 'best' model includes area as a predictor variable, runs with different predictor variables had r2 range from 0.70-0.79.
---
## XGboosted IVT Variable Importance

![image](https://github.com/orhuna/ar_ivt/assets/114206053/799fbc21-4d9b-40d9-a812-d05e6462bc8d)

---

**Comment by kellyrmat** [comment]
I pushed the wrong jupyter notebook. I'm working on getting the right one committed and pushed.

**Comment by orhuna** [comment]
Completed. Closing
