### ISSUE TITLE
Stratified XGBoost

### ISSUE THREAD

**Issue by orhuna** [orhuna/ar_ivt#6]
Define and find the optimal model for ARs clusters defined in issue #5 .

This issue should leverage code developed for issues #3 and #4 .

**Closing Criteria**
- [x] Model diagnostics for optimal models in the issue
- [x] Code that has clustering as an option

**Comment by kellyrmat** [comment]
@orhuna I pushed the code that makes stratified models for each cluster. The model configurations are saved as text files, used to initialize the XGB models for SHAPley plots. I'm reorganizing and going to make another directory off main that contains data, once I figure out how to do that.

**Comment by orhuna** [comment]
Merged to master. 🚢 🚢
