### ISSUE TITLE
XGBoost SHAPley Values

### ISSUE THREAD

**Issue by orhuna** [orhuna/ar_ivt#7]
Implement Shapley values for XGBoost output.

Closing criteria
- [x] SHAP plot for the global XGBoost model
- [x] SHAP plot for stratified XGBoost models
- [x] Push code for SHAP visualizations

**Comment by orhuna** [comment]
@kellyrmat please take a look at this reference for [SHAP analysis for XGBoost models](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/tree_based_models/Basic%20SHAP%20Interaction%20Value%20Example%20in%20XGBoost.html)

**Comment by kellyrmat** [comment]
@orhuna I've gotten Shapley working in a different environment and have finally made some plots for the global model. 
## **Beeswarm Plot**
![image](https://github.com/orhuna/ar_ivt/assets/114206053/0a1941a2-8255-46c4-b115-92bd466c2e06)

*To me, this shows some interesting and promising results and if I'm interpreting correctly... :*
- ARs rooted in lower latitudes, closer to the tropics, tend to have higher IVT (centroid_y). 
- ARs typically have stronger IVT when they're centered over the ocean (centroid_x).
- ENSO+, El Nino, years may produce weaker (<IVT) ARs in our domain while La Nina may favor strong ARs (>IVT)
- Positive PNA conditions yield ARs with higher vapor transport while negative conditions yield the opposite
- "Curvature" along the track matters; the less deviation in the AR's course along its track, the higher the AR's IVT
- "Displacement" of the AR along its track also matters, longer distance travelled -> higher IVT
- Interestingly, month does not tend to have a high shap value. 

## **Bar Plot**
![image](https://github.com/orhuna/ar_ivt/assets/114206053/7206623c-f804-418f-a6e8-050cf02739bd)
-Shows order of feature importance, but not as informative as the beeswarm plot, in my opinion
-Location, distance travelled, ENSO conditions, and PNA pattern are highly important

**Comment by kellyrmat** [comment]
@orhuna I've stratified the AR Climatology according to the Hausdorff Clusters in issue #5. 

I've copied the scatterplot from issue #5 here to help with interpreting the clustering+SHAP plots
## **Clustering Visualization**
![image](https://github.com/orhuna/ar_ivt/assets/114206053/9ed489c9-0d9c-48bb-9bfa-6a69345ccfa5)
- Cluster 0 "Mexican-Pacific Regime"
- Cluster 1 "West Coast Landfalling Regime"
- Cluster 2 "Pacific/West Coast Transitional Regime"
- Cluster 3 "Pacific Regime"

## Mexican-Pacific Regime
![image](https://github.com/orhuna/ar_ivt/assets/114206053/e26d6009-cd04-49b1-8e73-4151c40cd1a9)
![image](https://github.com/orhuna/ar_ivt/assets/114206053/feb5eae3-f002-4ef2-8d03-371365077bc0)

## West Coast Landfalling Regime
![image](https://github.com/orhuna/ar_ivt/assets/114206053/b389634f-4aad-4c0e-83d7-6708eb26acf5)
![image](https://github.com/orhuna/ar_ivt/assets/114206053/eef30d7f-15c4-48ac-a18d-cc4bc1ccb256)

## Pacific/West Coast Transitional Regime
![image](https://github.com/orhuna/ar_ivt/assets/114206053/be132909-6685-45bc-a7d8-6f8051a2aff0)
![image](https://github.com/orhuna/ar_ivt/assets/114206053/d029f122-87a7-4891-9cf5-10e23d831825)

## Pacific Regime
![image](https://github.com/orhuna/ar_ivt/assets/114206053/a3dc5b9d-d252-40df-afa8-b2a5cf6d9faf)
![image](https://github.com/orhuna/ar_ivt/assets/114206053/64d56c86-d77f-4e34-9888-87996cceedcb)

**Comment by orhuna** [comment]
Merged to master. 🚢 🚢
